# Generated by Django 5.2 on 2025-04-19 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
