# Generated by Django 5.2 on 2025-04-19 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_comentarios_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='contenido',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='creado',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='actualizado',
            new_name='updated',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Comentario al que responde', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
