# Generated by Django 5.2 on 2025-04-26 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='imagen',
            field=models.ImageField(default='default/user.png', null=True, upload_to='fotos_perfil'),
        ),
    ]
